In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime
import time

In [29]:
from sodapy import Socrata

MyAppToken = "XHmPxZYNeM0fs9qRHqHM2E968"
SecretToken = "vgBpaA8ZvWlF7xrJYBSSevJEy2bYetLz7ucp"
# Example authenticated client (needed for non-public datasets):
client = Socrata("data.cityofnewyork.us",
                MyAppToken,
                username="nl2600@columbia.edu",
                password="kyTbuq-myfpeg-3jedqi")

#LGA 40.766 ~ 40.780, -73.888 ~ -73.860
#JFK 40.64 ~ 40.65, -73.795 ~ -73.775
#NWK 40.675 - 40.705, -74.19 ~ -74.1745

num_loops = 20
loop_size = 50000
data = []
# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
for i in range(num_loops):
    results = client.get("uacg-pexx",
                     select="dropoff_latitude, dropoff_longitude, fare_amount, pickup_latitude, pickup_longitude, tpep_dropoff_datetime, tpep_pickup_datetime, trip_distance",
                     where="(dropoff_latitude>40.675 and dropoff_latitude<40.705) and (dropoff_longitude>-74.19 and dropoff_longitude<-74.1745)", 
                     order="tpep_pickup_datetime ASC",
                     limit=loop_size,
                     offset=loop_size * i)
    
    print("\r{}".format(i))
    for result in results:
        data.append(result)
    time.sleep(30)    
# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(data)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

In [30]:
results_df.tail(20)

,dropoff_latitude,dropoff_longitude,fare_amount,pickup_latitude,pickup_longitude,tpep_dropoff_datetime,tpep_pickup_datetime,trip_distance
119324,40.695121765136719,-74.177291870117187,85,40.757900238037109,-73.974746704101563,2016-06-30T20:12:05.000,2016-06-30T19:46:28.000,18.01
119325,40.695083618164063,-74.177299499511719,66,40.756011962890625,-73.990829467773437,2016-06-30T20:30:18.000,2016-06-30T19:54:11.000,16.73
119326,40.695274353027344,-74.177528381347656,80,40.695232391357422,-74.177574157714844,2016-06-30T20:02:34.000,2016-06-30T20:01:57.000,0
119327,40.690643310546875,-74.177421569824219,69.5,40.7720947265625,-73.9903564453125,2016-06-30T21:01:48.000,2016-06-30T20:19:39.000,17.7
119328,40.688022613525391,-74.18328857421875,67,40.704914093017578,-74.007476806640625,2016-06-30T21:13:30.000,2016-06-30T20:26:33.000,16.07
119329,40.693439483642578,-74.176773071289063,69,40.71575927734375,-73.989776611328125,2016-06-30T21:31:55.000,2016-06-30T20:36:20.000,14.39
119330,40.695503234863281,-74.177787780761719,94,40.769683837890625,-73.863807678222656,2016-06-30T21:49:11.000,2016-06-30T20:36:31.000,24.01
119331,40.692115783691406,-74.181259155273438,70.5,40.727893829345703,-73.991058349609375,2016-06-30T21:38:30.000,2016-06-30T20:45:10.000,15.7
119332,40.692008972167969,-74.1812744140625,94,40.774143218994141,-73.872909545898438,2016-06-30T22:21:37.000,2016-06-30T21:15:26.000,25.37
119333,40.695873260498047,-74.188262939453125,90.5,40.756420135498047,-73.991111755371094,2016-06-30T22:48:32.000,2016-06-30T21:21:37.000,17.24
119334,40.7034912109375,-74.185493469238281,80,40.755340576171875,-73.984992980957031,2016-06-30T21:54:55.000,2016-06-30T21:25:19.000,14.73
119335,40.690570831298828,-74.177520751953125,85.5,40.765720367431641,-73.958961486816406,2016-06-30T23:03:09.000,2016-06-30T22:13:24.000,23.94
119336,40.689727783203125,-74.178192138671875,95,40.690425872802734,-73.984375,2016-07-01T00:00:54.000,2016-06-30T22:15:19.000,15.5
119337,40.690269470214844,-74.177749633789062,76,40.751129150390625,-73.939872741699219,2016-06-30T23:34:31.000,2016-06-30T22:48:16.000,20.34
119338,40.690971374511719,-74.178131103515625,135,40.644989013671875,-73.788566589355469,2016-07-01T00:18:17.000,2016-06-30T22:53:49.000,31.69
119339,40.700908660888672,-74.187248229980469,133.5,40.647171020507813,-73.789688110351563,2016-07-01T01:09:01.000,2016-06-30T23:10:07.000,36.07
119340,40.690784454345703,-74.177528381347656,63,40.7646484375,-73.985870361328125,2016-06-30T23:49:41.000,2016-06-30T23:20:09.000,16.85
119341,40.687961578369141,-74.183128356933594,99,40.773998260498047,-73.873397827148438,2016-07-01T00:48:47.000,2016-06-30T23:27:26.000,25.3
119342,40.698993682861328,-74.187149047851563,122,40.648670196533203,-73.783607482910156,2016-07-01T00:43:41.000,2016-06-30T23:36:57.000,40.2
119343,40.690067291259766,-74.177848815917969,71.5,40.752975463867188,-73.983444213867188,2016-07-01T00:29:16.000,2016-06-30T23:49:07.000,19.3

Why are there 0 for longitude and latitude?

In [31]:
print(results_df.shape)
results_df = results_df[results_df["trip_distance"] != "0"]
print(results_df.shape)

(119344, 8)
(116000, 8)

In [32]:
np.mean(results_df.trip_distance.astype("float"))

17.61639284482809

In [33]:
results_df.tpep_dropoff_datetime = pd.to_datetime(results_df.tpep_dropoff_datetime)
results_df.tpep_pickup_datetime = pd.to_datetime(results_df.tpep_pickup_datetime)

In [34]:
results_df["travelTime"] = pd.to_timedelta(results_df.tpep_dropoff_datetime - results_df.tpep_pickup_datetime)
results_df["travelTime"]

0        00:40:09
1        00:23:32
2        00:30:38
3        00:30:33
4        00:47:09
5        00:57:52
6        00:29:34
7        00:32:33
8        00:16:32
9        00:42:42
11       00:39:35
12       00:21:42
13       00:51:40
14       00:24:12
15       00:30:31
16       00:40:56
17       00:35:57
18       00:29:26
19       00:27:09
20       00:30:06
21       00:27:50
22       00:24:00
23       00:48:58
24       00:34:40
25       00:28:27
26       00:31:51
27       00:25:13
28       00:17:24
29       00:26:53
30       00:22:23
           ...
119311   00:38:38
119312   00:53:37
119313   00:53:42
119314   00:37:26
119315   00:00:21
119316   00:00:20
119317   00:54:37
119318   00:45:03
119319   00:42:05
119321   00:58:17
119323   01:14:11
119324   00:25:37
119325   00:36:07
119327   00:42:09
119328   00:46:57
119329   00:55:35
119330   01:12:40
119331   00:53:20
119332   01:06:11
119333   01:26:55
119334   00:29:36
119335   00:49:45
119336   01:45:35
119337   00:46:15
119338   01:24:28
119339   01:58:54
119340   00:29:32
119341   01:21:21
119342   01:06:44
119343   00:40:09
Name: travelTime, Length: 116000, dtype: timedelta64[ns]

In [35]:
results_df.to_csv("../output/NWK_data.csv")